
package Lexer;


public enum TokenType {
    PLUSSYM, MINUSSYM, MULTSYM, DIVSYM, POWSYM, LPARENTSYM, RPARENTSYM, NUMBERSYM, 
    IDENTSYM, SINSYM, COSSYM, TANSYM, LNSYM, LOGSYM, CSCSYM, SECSYM, COTSYM,
    ARCSINSYM, ARCCOSSYM, ARCTANSYM, ARCCSCSYM, ARCSECSYM, ARCCOTSYM
}

